on:
  pull_request:
  merge_group:

name: build

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
            components: rustfmt, clippy

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy
      - name: Test
        run: |
          cargo test
